# Generated by Django 4.2.19 on 2025-07-11 08:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screenshots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenshot',
            name='file',
            field=models.FileField(help_text='An image file of the screenshot (static or animated GIF). The file size must be less than 10MB.', upload_to='screenshots/%Y', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'gif', 'svg', 'webp', 'tiff', 'bmp'])], verbose_name='Screenshot Image File'),
        ),
    ]
