# Generated by Django 4.2.18 on 2025-02-12 11:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('styles', '0016_style_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='style',
            name='file',
            field=models.FileField(help_text='A QGIS Style (.xml) or Color Palette (.gpl) file.', upload_to='styles/%Y', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xml', 'gpl'])], verbose_name='Style file'),
        ),
    ]
