# Generated by Django 4.2.19 on 2025-02-20 06:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('styles', '0017_alter_style_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='style',
            name='file',
            field=models.FileField(help_text='Upload a QGIS Style (.xml) or a Color Palette (.gpl) file.', upload_to='styles/%Y', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xml', 'gpl'])], verbose_name='Style file'),
        ),
    ]
