# Generated by Django 4.2.19 on 2025-09-09 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('styles', '0018_alter_style_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='style_types',
            field=models.ManyToManyField(blank=True, help_text='The types of this style, these will automatically be read from the XML file.', related_name='styles', to='styles.styletype', verbose_name='Style Types'),
        ),
    ]
