# Generated by Django 4.2.19 on 2025-02-28 06:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('map_gallery', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MapSubmission',
            new_name='Map',
        ),
    ]
