# Generated by Django 4.2.19 on 2025-04-02 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_gallery', '0002_rename_mapsubmission_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='is_publishable',
            field=models.BooleanField(default=False, help_text='Is this map eligible to be published on QGIS.org?', verbose_name='Is Publishable'),
        ),
    ]
