# Generated by Django 4.2.30 on 2026-04-28 18:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processing_scripts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PyQtVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="PyQt version name (e.g., PyQt5, PyQt6)",
                        max_length=50,
                        unique=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="A short description of this PyQt version.",
                        max_length=500,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0,
                        help_text="Order value for display sorting.",
                        verbose_name="Order",
                    ),
                ),
            ],
            options={
                "verbose_name": "PyQt Version",
                "verbose_name_plural": "PyQt Versions",
                "ordering": ("order", "name"),
            },
        ),
        migrations.AlterField(
            model_name="processingscript",
            name="file",
            field=models.FileField(
                help_text="A Python file. The filesize must be less than 1MB.",
                upload_to="processing_scripts/%Y",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["py"]
                    )
                ],
                verbose_name="Processing script file",
            ),
        ),
        migrations.AlterField(
            model_name="processingscript",
            name="thumbnail_image",
            field=models.ImageField(
                help_text="Please upload an image that demonstrate this Script. Max size is 2MB.",
                upload_to="processing_scripts/%Y",
                verbose_name="Thumbnail",
            ),
        ),
        migrations.AddField(
            model_name="processingscript",
            name="pyqt_versions",
            field=models.ManyToManyField(
                blank=True,
                help_text="The PyQt versions this script is compatible with",
                related_name="processing_scripts",
                to="processing_scripts.pyqtversion",
                verbose_name="PyQt Versions",
            ),
        ),
    ]
