# Generated by Django 4.2.30 on 2026-04-28 18:32

from django.db import migrations


def populate_pyqt_versions(apps, schema_editor):
    """Populate initial PyQt version data"""
    PyQtVersion = apps.get_model("processing_scripts", "PyQtVersion")

    pyqt_versions = [
        {"name": "PyQt5", "description": "PyQt5 - Python bindings for Qt5", "order": 1},
        {"name": "PyQt6", "description": "PyQt6 - Python bindings for Qt6", "order": 2},
    ]

    for version_data in pyqt_versions:
        PyQtVersion.objects.get_or_create(
            name=version_data["name"],
            defaults={
                "description": version_data["description"],
                "order": version_data["order"],
            },
        )


def reverse_populate_pyqt_versions(apps, schema_editor):
    """Remove initial PyQt version data"""
    PyQtVersion = apps.get_model("processing_scripts", "PyQtVersion")
    PyQtVersion.objects.filter(name__in=["PyQt5", "PyQt6"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("processing_scripts", "0002_pyqtversion_alter_processingscript_file_and_more"),
    ]

    operations = [
        migrations.RunPython(populate_pyqt_versions, reverse_populate_pyqt_versions),
    ]
