# Generated by Django 4.2.18 on 2025-02-03 09:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geopackages', '0010_geopackage_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geopackage',
            name='file',
            field=models.FileField(help_text='A GeoPackage file. The filesize must less than 5MB ', upload_to='geopackages/%Y', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['gpkg', 'zip'])], verbose_name='GeoPackage file'),
        ),
    ]
