name: Build and Push Docker Image

on:
  push:
    tags:
      - '*'
  workflow_dispatch:   # Allows you to run this workflow manually from the Actions tab

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }} # Using token is recommended

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: dockerize/docker/Dockerfile
        push: true
        tags: |
          qgis/qgis-hub-uwsgi:${{ github.ref_name }}
          qgis/qgis-hub-uwsgi:latest

    - name: Log out from Docker Hub
      run: docker logout
